/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as EncontradosRouteImport } from './routes/encontrados'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MeuEspacoRouteImport } from './routes/meu-espaco'
import { Route as PerdidosRouteImport } from './routes/perdidos'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAvisosRouteImport } from './routes/admin.avisos'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminDenunciasRouteImport } from './routes/admin.denuncias'
import { Route as AdminMunicipiosRouteImport } from './routes/admin.municipios'
import { Route as AdminOcorrenciasRouteImport } from './routes/admin.ocorrencias'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminUtilizadoresRouteImport } from './routes/admin.utilizadores'
import { Route as MeuEspacoIndexRouteImport } from './routes/meu-espaco.index'
import { Route as MeuEspacoConfiguracoesRouteImport } from './routes/meu-espaco.configuracoes'
import { Route as MeuEspacoFavoritosRouteImport } from './routes/meu-espaco.favoritos'
import { Route as MeuEspacoMensagensRouteImport } from './routes/meu-espaco.mensagens'
import { Route as MeuEspacoNotificacoesRouteImport } from './routes/meu-espaco.notificacoes'
import { Route as MeuEspacoOcorrenciasRouteImport } from './routes/meu-espaco.ocorrencias'
import { Route as MeuEspacoPerfilRouteImport } from './routes/meu-espaco.perfil'
import { Route as OcorrenciaIdRouteImport } from './routes/ocorrencia.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EncontradosRoute = EncontradosRouteImport.update({
  id: '/encontrados',
  path: '/encontrados',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuEspacoRoute = MeuEspacoRouteImport.update({
  id: '/meu-espaco',
  path: '/meu-espaco',
  getParentRoute: () => rootRouteImport,
} as any)
const PerdidosRoute = PerdidosRouteImport.update({
  id: '/perdidos',
  path: '/perdidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvisosRoute = AdminAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDenunciasRoute = AdminDenunciasRouteImport.update({
  id: '/denuncias',
  path: '/denuncias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMunicipiosRoute = AdminMunicipiosRouteImport.update({
  id: '/municipios',
  path: '/municipios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOcorrenciasRoute = AdminOcorrenciasRouteImport.update({
  id: '/ocorrencias',
  path: '/ocorrencias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUtilizadoresRoute = AdminUtilizadoresRouteImport.update({
  id: '/utilizadores',
  path: '/utilizadores',
  getParentRoute: () => AdminRoute,
} as any)
const MeuEspacoIndexRoute = MeuEspacoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeuEspacoRoute,
} as any)
const MeuEspacoConfiguracoesRoute = MeuEspacoConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => MeuEspacoRoute,
} as any)
const MeuEspacoFavoritosRoute = MeuEspacoFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => MeuEspacoRoute,
} as any)
const MeuEspacoMensagensRoute = MeuEspacoMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => MeuEspacoRoute,
} as any)
const MeuEspacoNotificacoesRoute = MeuEspacoNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => MeuEspacoRoute,
} as any)
const MeuEspacoOcorrenciasRoute = MeuEspacoOcorrenciasRouteImport.update({
  id: '/ocorrencias',
  path: '/ocorrencias',
  getParentRoute: () => MeuEspacoRoute,
} as any)
const MeuEspacoPerfilRoute = MeuEspacoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => MeuEspacoRoute,
} as any)
const OcorrenciaIdRoute = OcorrenciaIdRouteImport.update({
  id: '/ocorrencia/$id',
  path: '/ocorrencia/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/avisos': typeof AvisosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contactos': typeof ContactosRoute
  '/criar-conta': typeof CriarContaRoute
  '/encontrados': typeof EncontradosRoute
  '/entrar': typeof EntrarRoute
  '/meu-espaco': typeof MeuEspacoRouteWithChildren
  '/perdidos': typeof PerdidosRoute
  '/publicar': typeof PublicarRoute
  '/admin/avisos': typeof AdminAvisosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/municipios': typeof AdminMunicipiosRoute
  '/admin/ocorrencias': typeof AdminOcorrenciasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/meu-espaco/configuracoes': typeof MeuEspacoConfiguracoesRoute
  '/meu-espaco/favoritos': typeof MeuEspacoFavoritosRoute
  '/meu-espaco/mensagens': typeof MeuEspacoMensagensRoute
  '/meu-espaco/notificacoes': typeof MeuEspacoNotificacoesRoute
  '/meu-espaco/ocorrencias': typeof MeuEspacoOcorrenciasRoute
  '/meu-espaco/perfil': typeof MeuEspacoPerfilRoute
  '/ocorrencia/$id': typeof OcorrenciaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/meu-espaco/': typeof MeuEspacoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contactos': typeof ContactosRoute
  '/criar-conta': typeof CriarContaRoute
  '/encontrados': typeof EncontradosRoute
  '/entrar': typeof EntrarRoute
  '/perdidos': typeof PerdidosRoute
  '/publicar': typeof PublicarRoute
  '/admin/avisos': typeof AdminAvisosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/municipios': typeof AdminMunicipiosRoute
  '/admin/ocorrencias': typeof AdminOcorrenciasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/meu-espaco/configuracoes': typeof MeuEspacoConfiguracoesRoute
  '/meu-espaco/favoritos': typeof MeuEspacoFavoritosRoute
  '/meu-espaco/mensagens': typeof MeuEspacoMensagensRoute
  '/meu-espaco/notificacoes': typeof MeuEspacoNotificacoesRoute
  '/meu-espaco/ocorrencias': typeof MeuEspacoOcorrenciasRoute
  '/meu-espaco/perfil': typeof MeuEspacoPerfilRoute
  '/ocorrencia/$id': typeof OcorrenciaIdRoute
  '/admin': typeof AdminIndexRoute
  '/meu-espaco': typeof MeuEspacoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/avisos': typeof AvisosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contactos': typeof ContactosRoute
  '/criar-conta': typeof CriarContaRoute
  '/encontrados': typeof EncontradosRoute
  '/entrar': typeof EntrarRoute
  '/meu-espaco': typeof MeuEspacoRouteWithChildren
  '/perdidos': typeof PerdidosRoute
  '/publicar': typeof PublicarRoute
  '/admin/avisos': typeof AdminAvisosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/municipios': typeof AdminMunicipiosRoute
  '/admin/ocorrencias': typeof AdminOcorrenciasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/meu-espaco/configuracoes': typeof MeuEspacoConfiguracoesRoute
  '/meu-espaco/favoritos': typeof MeuEspacoFavoritosRoute
  '/meu-espaco/mensagens': typeof MeuEspacoMensagensRoute
  '/meu-espaco/notificacoes': typeof MeuEspacoNotificacoesRoute
  '/meu-espaco/ocorrencias': typeof MeuEspacoOcorrenciasRoute
  '/meu-espaco/perfil': typeof MeuEspacoPerfilRoute
  '/ocorrencia/$id': typeof OcorrenciaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/meu-espaco/': typeof MeuEspacoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/avisos'
    | '/como-funciona'
    | '/contactos'
    | '/criar-conta'
    | '/encontrados'
    | '/entrar'
    | '/meu-espaco'
    | '/perdidos'
    | '/publicar'
    | '/admin/avisos'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/denuncias'
    | '/admin/municipios'
    | '/admin/ocorrencias'
    | '/admin/relatorios'
    | '/admin/utilizadores'
    | '/meu-espaco/configuracoes'
    | '/meu-espaco/favoritos'
    | '/meu-espaco/mensagens'
    | '/meu-espaco/notificacoes'
    | '/meu-espaco/ocorrencias'
    | '/meu-espaco/perfil'
    | '/ocorrencia/$id'
    | '/admin/'
    | '/meu-espaco/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avisos'
    | '/como-funciona'
    | '/contactos'
    | '/criar-conta'
    | '/encontrados'
    | '/entrar'
    | '/perdidos'
    | '/publicar'
    | '/admin/avisos'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/denuncias'
    | '/admin/municipios'
    | '/admin/ocorrencias'
    | '/admin/relatorios'
    | '/admin/utilizadores'
    | '/meu-espaco/configuracoes'
    | '/meu-espaco/favoritos'
    | '/meu-espaco/mensagens'
    | '/meu-espaco/notificacoes'
    | '/meu-espaco/ocorrencias'
    | '/meu-espaco/perfil'
    | '/ocorrencia/$id'
    | '/admin'
    | '/meu-espaco'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/avisos'
    | '/como-funciona'
    | '/contactos'
    | '/criar-conta'
    | '/encontrados'
    | '/entrar'
    | '/meu-espaco'
    | '/perdidos'
    | '/publicar'
    | '/admin/avisos'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/denuncias'
    | '/admin/municipios'
    | '/admin/ocorrencias'
    | '/admin/relatorios'
    | '/admin/utilizadores'
    | '/meu-espaco/configuracoes'
    | '/meu-espaco/favoritos'
    | '/meu-espaco/mensagens'
    | '/meu-espaco/notificacoes'
    | '/meu-espaco/ocorrencias'
    | '/meu-espaco/perfil'
    | '/ocorrencia/$id'
    | '/admin/'
    | '/meu-espaco/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AvisosRoute: typeof AvisosRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContactosRoute: typeof ContactosRoute
  CriarContaRoute: typeof CriarContaRoute
  EncontradosRoute: typeof EncontradosRoute
  EntrarRoute: typeof EntrarRoute
  MeuEspacoRoute: typeof MeuEspacoRouteWithChildren
  PerdidosRoute: typeof PerdidosRoute
  PublicarRoute: typeof PublicarRoute
  OcorrenciaIdRoute: typeof OcorrenciaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encontrados': {
      id: '/encontrados'
      path: '/encontrados'
      fullPath: '/encontrados'
      preLoaderRoute: typeof EncontradosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-espaco': {
      id: '/meu-espaco'
      path: '/meu-espaco'
      fullPath: '/meu-espaco'
      preLoaderRoute: typeof MeuEspacoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perdidos': {
      id: '/perdidos'
      path: '/perdidos'
      fullPath: '/perdidos'
      preLoaderRoute: typeof PerdidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avisos': {
      id: '/admin/avisos'
      path: '/avisos'
      fullPath: '/admin/avisos'
      preLoaderRoute: typeof AdminAvisosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/denuncias': {
      id: '/admin/denuncias'
      path: '/denuncias'
      fullPath: '/admin/denuncias'
      preLoaderRoute: typeof AdminDenunciasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/municipios': {
      id: '/admin/municipios'
      path: '/municipios'
      fullPath: '/admin/municipios'
      preLoaderRoute: typeof AdminMunicipiosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ocorrencias': {
      id: '/admin/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/admin/ocorrencias'
      preLoaderRoute: typeof AdminOcorrenciasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/utilizadores': {
      id: '/admin/utilizadores'
      path: '/utilizadores'
      fullPath: '/admin/utilizadores'
      preLoaderRoute: typeof AdminUtilizadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/meu-espaco/': {
      id: '/meu-espaco/'
      path: '/'
      fullPath: '/meu-espaco/'
      preLoaderRoute: typeof MeuEspacoIndexRouteImport
      parentRoute: typeof MeuEspacoRoute
    }
    '/meu-espaco/configuracoes': {
      id: '/meu-espaco/configuracoes'
      path: '/configuracoes'
      fullPath: '/meu-espaco/configuracoes'
      preLoaderRoute: typeof MeuEspacoConfiguracoesRouteImport
      parentRoute: typeof MeuEspacoRoute
    }
    '/meu-espaco/favoritos': {
      id: '/meu-espaco/favoritos'
      path: '/favoritos'
      fullPath: '/meu-espaco/favoritos'
      preLoaderRoute: typeof MeuEspacoFavoritosRouteImport
      parentRoute: typeof MeuEspacoRoute
    }
    '/meu-espaco/mensagens': {
      id: '/meu-espaco/mensagens'
      path: '/mensagens'
      fullPath: '/meu-espaco/mensagens'
      preLoaderRoute: typeof MeuEspacoMensagensRouteImport
      parentRoute: typeof MeuEspacoRoute
    }
    '/meu-espaco/notificacoes': {
      id: '/meu-espaco/notificacoes'
      path: '/notificacoes'
      fullPath: '/meu-espaco/notificacoes'
      preLoaderRoute: typeof MeuEspacoNotificacoesRouteImport
      parentRoute: typeof MeuEspacoRoute
    }
    '/meu-espaco/ocorrencias': {
      id: '/meu-espaco/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/meu-espaco/ocorrencias'
      preLoaderRoute: typeof MeuEspacoOcorrenciasRouteImport
      parentRoute: typeof MeuEspacoRoute
    }
    '/meu-espaco/perfil': {
      id: '/meu-espaco/perfil'
      path: '/perfil'
      fullPath: '/meu-espaco/perfil'
      preLoaderRoute: typeof MeuEspacoPerfilRouteImport
      parentRoute: typeof MeuEspacoRoute
    }
    '/ocorrencia/$id': {
      id: '/ocorrencia/$id'
      path: '/ocorrencia/$id'
      fullPath: '/ocorrencia/$id'
      preLoaderRoute: typeof OcorrenciaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAvisosRoute: typeof AdminAvisosRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDenunciasRoute: typeof AdminDenunciasRoute
  AdminMunicipiosRoute: typeof AdminMunicipiosRoute
  AdminOcorrenciasRoute: typeof AdminOcorrenciasRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminUtilizadoresRoute: typeof AdminUtilizadoresRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAvisosRoute: AdminAvisosRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDenunciasRoute: AdminDenunciasRoute,
  AdminMunicipiosRoute: AdminMunicipiosRoute,
  AdminOcorrenciasRoute: AdminOcorrenciasRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminUtilizadoresRoute: AdminUtilizadoresRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MeuEspacoRouteChildren {
  MeuEspacoConfiguracoesRoute: typeof MeuEspacoConfiguracoesRoute
  MeuEspacoFavoritosRoute: typeof MeuEspacoFavoritosRoute
  MeuEspacoMensagensRoute: typeof MeuEspacoMensagensRoute
  MeuEspacoNotificacoesRoute: typeof MeuEspacoNotificacoesRoute
  MeuEspacoOcorrenciasRoute: typeof MeuEspacoOcorrenciasRoute
  MeuEspacoPerfilRoute: typeof MeuEspacoPerfilRoute
  MeuEspacoIndexRoute: typeof MeuEspacoIndexRoute
}

const MeuEspacoRouteChildren: MeuEspacoRouteChildren = {
  MeuEspacoConfiguracoesRoute: MeuEspacoConfiguracoesRoute,
  MeuEspacoFavoritosRoute: MeuEspacoFavoritosRoute,
  MeuEspacoMensagensRoute: MeuEspacoMensagensRoute,
  MeuEspacoNotificacoesRoute: MeuEspacoNotificacoesRoute,
  MeuEspacoOcorrenciasRoute: MeuEspacoOcorrenciasRoute,
  MeuEspacoPerfilRoute: MeuEspacoPerfilRoute,
  MeuEspacoIndexRoute: MeuEspacoIndexRoute,
}

const MeuEspacoRouteWithChildren = MeuEspacoRoute._addFileChildren(
  MeuEspacoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AvisosRoute: AvisosRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContactosRoute: ContactosRoute,
  CriarContaRoute: CriarContaRoute,
  EncontradosRoute: EncontradosRoute,
  EntrarRoute: EntrarRoute,
  MeuEspacoRoute: MeuEspacoRouteWithChildren,
  PerdidosRoute: PerdidosRoute,
  PublicarRoute: PublicarRoute,
  OcorrenciaIdRoute: OcorrenciaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
